sudo: false
language: python
matrix:
  include:
    - arch: arm64
      python: 2.7
    - arch: amd64
      python: 2.7
    - arch: arm64
      python: 3.4
    - arch: amd64
      python: 3.4
    - arch: arm64
      python: 3.5
    - arch: amd64
      python: 3.5
    - arch: arm64
      python: 3.6
    - arch: amd64
      python: 3.6
    - arch: arm64
      python: 3.7
    - arch: amd64
      python: 3.7
    - arch: amd64
      python: pypy
    - arch: amd64
      python: pypy3
install: pip install tox-travis
script: tox
