sudo: false
language: python
matrix:
  include:
    - arch: arm64
    - "2.6"
    - arch: amd64
    - "2.6"
    - arch: arm64
    - "2.7"
    - arch: amd64
    - "2.7"
    - arch: arm64
    - "3.3"
    - arch: amd64
    - "3.3"
    - arch: arm64
    - "3.4"
    - arch: amd64
    - "3.4"
    - arch: arm64
    - "3.5"
    - arch: amd64
    - "3.5"
    - arch: arm64
    - "pypy"
    - arch: amd64
    - "pypy"
    - arch: arm64
    - "pypy3"
    - arch: amd64
    - "pypy3"
install: pip install tox-travis
script: tox
